name: Container

on:
  push:
    branches:
      - '*'
  pull_request:
    types: [opened, reopened]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  CONTAINER_IMAGE: quay.io/robszumski/cncjs:latest

jobs:
  build-container:
    runs-on: ubuntu-latest
    outputs:
      container_image: ${{ env.CONTAINER_IMAGE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        id: build-4Yc7j8
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.CONTAINER_IMAGE }}

      - name: Push Image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          docker push ${{ env.CONTAINER_IMAGE }}
      
      - name: Download Syft
        id: syft
        uses: anchore/sbom-action/download-syft@v0.14.2
      
      - name: Generate SBOM from the container
        run: "${{ steps.syft.outputs.cmd }} --config .github/edgebit/build-syft.yaml --file /tmp/sbom.syft.json ${{ steps.build-4Yc7j8.outputs.digest }}"
      
      - name: Upload SBOM
        uses: actions/upload-artifact@v3
        with:
          name: edgebit-sbom
          path: /tmp/sbom.syft.json
